apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: portfolio-staging
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: frontend
            wave: "2"
          - service: backend
            wave: "3"
  template:
    metadata:
      name: '{{service}}-staging'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: staging
      source:
        repoURL: https://github.com/sahar449/my-portfolio-multi-env.git
        targetRevision: HEAD
        path: 'ArgoCD/{{service}}/helm_chart'
        helm:
          valueFiles:
            - values.staging.yaml
      destination:
        name: eksdemo-staging-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
