apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backend.name" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
