apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets.serviceAccountName }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.secrets.accountNumber }}:role/flask-app-secrets-role
