app:
  name: frontend
  namespace: default
  replicas: 1
  image:
    repository: "ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/frontend-staging"
    tag: "a02ce2a2e4f51bbedd5bb7962faf59869f2ca5cb"
    pullPolicy: Always
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
pdb:
  minAvailable: 1
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m
ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/tags: ManagedBy=argocd,Application=portfolio,Environment=staging
    alb.ingress.kubernetes.io/load-balancer-name: portfolio-staging-alb
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=false
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
    external-dns.alpha.kubernetes.io/hostname: stage.saharbittman.com
  hosts:
    - host: stage.saharbittman.com
      paths:
        - path: /api/backend
          pathType: Prefix
          service: backend
          port: 5002
        - path: /
          pathType: Prefix
          service: frontend
          port: 5000
  tls:
    - hosts:
        - '*.saharbittman.com'
