apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alb-controller
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: staging
            cluster: eksdemo-staging-cluster
            clusterName: eksdemo-staging-cluster
            vpcId: "vpc-07712d7b0ffbf9c54"
            irsaRoleArn: "arn:aws:iam::634647866665:role/eksdemo-staging-lb-controller-role"
          - env: prod
            cluster: in-cluster
            clusterName: eksdemo-prod-cluster
            vpcId: "vpc-0c9b6471e9ff22617"
            irsaRoleArn: "arn:aws:iam::634647866665:role/eksdemo-prod-lb-controller-role"
  template:
    metadata:
      name: "alb-controller-{{env}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: https://aws.github.io/eks-charts
        chart: aws-load-balancer-controller
        targetRevision: 1.8.3
        helm:
          values: |
            clusterName: "{{clusterName}}"
            region: us-west-2
            vpcId: "{{vpcId}}"
            serviceAccount:
              create: true
              name: aws-load-balancer-controller
              annotations:
                eks.amazonaws.com/role-arn: "{{irsaRoleArn}}"
      destination:
        name: "{{cluster}}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
