apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.3
    helm:
      values: |
        clusterName: "eksdemo-prod-cluster"
        region: us-west-2
        vpcId: "PROD_VPC_ID"
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eksdemo-prod-lb-controller-role"
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
