name: CI Dev

on:
  push:
    branches:
      - dev
      - 'feature/**'
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  build:
    uses: sahar449/my-portfolio-multi-env/.github/workflows/ci/ci-build.yaml@main
    with:
      environment: dev
    secrets: inherit
