name: CI Dev

on:
  push:
    branches:
      - dev
      - 'feature/**'
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci-build.yaml
    with:
      environment: dev
    secrets: inherit
