name: CI Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci-build.yaml
    with:
      environment: staging
    secrets: inherit
