name: CI Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  build:
    uses: sahar449/my-portfolio-multi-env/.github/workflows/ci-build.yaml@main
    with:
      environment: staging
    secrets: inherit
